EXP_DIR: ycb_dataset
CODE_DIM: 128
CAPACITY: 1
FULLY_CONV: False
TRAIN:
  OBJECTS: !!python/tuple ['006_mustard_bottle']
  BOOTSTRAP_CONST: 2000
  USE_TRIPLET_LOSS: False
  WORKERS: 0
  TRANS_SEP: False
  DEEPER_TRANSNET: True
  ONLINE_RENDERING: True
  RENDER_DIST: !!python/tuple [2.0]
  LIGHT_INT_MIN: 0.3
  LIGHT_INT_MAX: 3.0
  LIGHT_COLOR_VAR: 0.8
  LIGHT_R_MAX: 3.0
  LIGHT_R_MIN: 0.25
  TRANSNET_CAPACITY: !!python/tuple [10, 20, 32]
  SHIFT_MIN: -5.0
  SHIFT_MAX: 5.0
  SCALE_MIN: 0.975
  SCALE_MAX: 1.025
  OC_PROB: 0.3
  N_OCCLUDERS: 2
  TRUNC_PROB: 0.1
  TRUNC_X_MAX: 1.0
  TRUNC_Y_MAX: 1.0