EXP_DIR: ycb_dataset
CODE_DIM: 128
CAPACITY: 1
GPU_ID: 0
EXP_NAME: "fusion"
TRAIN:
  DEPTH_FUSION: True
  RoI_ACC: True
  TRAIN_TRANSNET: False
  TRAIN_AAE: True
  DEPTH_EMBEDDING: True
  OBJECTS: !!python/tuple ['037_scissors']
  BOOTSTRAP_CONST: 2000
  USE_TRIPLET_LOSS: False
  WORKERS: 0
  TRANS_SEP: False
  DEEPER_TRANSNET: True
  ONLINE_RENDERING: True
  RENDER_DIST: !!python/tuple [2.25]
  LIGHT_INT_MIN: 0.5
  LIGHT_INT_MAX: 2.0
  LIGHT_COLOR_VAR: 0.8
  LIGHT_R_MAX: 0.75
  LIGHT_R_MIN: 0.25
  TRANSNET_CAPACITY: !!python/tuple [10, 20, 32]
  SHIFT_MIN: -5.0
  SHIFT_MAX: 5.0
  SCALE_MIN: 0.975
  SCALE_MAX: 1.025
  OC_PROB: 0.3
  USE_OCCLUSION: True
  N_OCCLUDERS: 3
  TRUNC_PROB: 0.2
  OC_XY_RANGE: !!python/tuple [-0.1, 0.1]
  OC_Z_RANGE: !!python/tuple [0, 0.2]
  TRUNC_X_MAX: 1.0
  TRUNC_Y_MAX: 1.0
  INPUT_IM_SIZE: [256, 256]